apiVersion: v1
kind: Secret
metadata:
  name: redmine-env
  labels:
    app: redmine
    chart: redmine
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  
  DB_HOST: {{ .Values.postgresql.host | b64enc | quote }}
  DB_PORT: {{ .Values.postgresql.port  | b64enc | quote }}
  DB_USER: {{ .Values.postgresql.postgresqlUsername  | b64enc | quote }}
  DB_PASS: {{ .Values.postgresql.postgresqlPassword  | b64enc | quote }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase  | b64enc | quote }}

  SMTP_ENABLED: {{ .Values.smtp.enabled | b64enc | quote }}
  SMTP_METHOD: {{ .Values.smtp.method  | b64enc | quote }}
  SMTP_DOMAIN: {{ .Values.smtp.domain  | b64enc | quote }}
  SMTP_HOST: {{ .Values.smtp.host  | b64enc | quote }}
  SMTP_PORT: {{ .Values.smtp.port  | b64enc | quote }}
  SMTP_USER: {{ .Values.smtp.user  | b64enc | quote }}
  SMTP_PASS: {{ .Values.smtp.password  | b64enc | quote }}
  SMTP_STARTTLS: {{ .Values.smtp.starttls  | b64enc | quote }}
  SMTP_AUTHENTICATION: {{ .Values.smtp.authentication  | b64enc | quote }}


  IMAP_ENABLED: {{ .Values.imap.enabled  | b64enc | quote }}
  IMAP_HOST: {{ .Values.imap.host  | b64enc | quote }}
  IMAP_PORT: {{ .Values.imap.port  | b64enc | quote }}
  IMAP_USER: {{ .Values.imap.user  | b64enc | quote }}
  IMAP_PASS: {{ .Values.imap.password  | b64enc | quote }}
  IMAP_SSL: {{ .Values.imap.ssl  | b64enc | quote }}
  IMAP_INTERVAL: {{ .Values.imap.interval  | b64enc | quote }}
