apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.serviceAccount.name }}
    component: {{ .Values.serviceAccount.name }}
    
