apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-db
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: "/var/nfsshare/redmine/redmine-db"

