apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-dmsf
  labels:
    app: redmine-dmsf
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.7
    path: "/var/nfs-share/redmine/dmsf"

