apiVersion: v1
kind: PersistentVolume
metadata:
  name: redmine-info
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: "/var/nfsshare/redmine/redmine-info"

